#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
    touch $SERVICE_CONFIG
  fi

  config::check_or_set SERVICE_NPS_WEB_PORT text $SERVICE_CONFIG
  config::check_or_set SERVICE_NPS_TUNNEL_PORT text $SERVICE_CONFIG
  config::check_or_set SERVICE_NPS_OUT_PORTS text $SERVICE_CONFIG
  #
  config::check_or_set SERVICE_NPS_DOMAIN text $SERVICE_CONFIG
  config::check_or_set SERVICE_NPS_SECRET text $SERVICE_CONFIG
  #
  # config::check_or_set SERVICE_NPS_USERNAME yesno $SERVICE_CONFIG
  # config::check_or_set SERVICE_NPS_PASSWORD yesno $SERVICE_CONFIG
  #
  # config::check_or_set SERVICE_NPS_OAUTH2_ENABLE yesno $SERVICE_CONFIG
  # config::check_or_set SERVICE_NPS_OAUTH2_SERVER_URL yesno $SERVICE_CONFIG
  # config::check_or_set SERVICE_NPS_OAUTH2_CLIENT_ID yesno $SERVICE_CONFIG
  # config::check_or_set SERVICE_NPS_OAUTH2_CLIENT_SECRET yesno $SERVICE_CONFIG

  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_NPS_OAUTH2_ENABLE" ]; then
    local choices=(
      "Yes"
      "No"
    )
    inquirer::select "Enable OAUTH2 ?" choices value
    if [ "$value" = "Yes" ]; then
      export SERVICE_NPS_OAUTH2_ENABLE=true
    else
      export SERVICE_NPS_OAUTH2_ENABLE=false
    fi

    config::set SERVICE_NPS_OAUTH2_ENABLE $SERVICE_NPS_OAUTH2_ENABLE $SERVICE_CONFIG
  fi

  if [ "$SERVICE_NPS_OAUTH2_ENABLE" = "true" ]; then
    if [ -z "$SERVICE_NPS_OAUTH2_SERVER_URL" ]; then
      inquirer::text "请输入 SERVICE_NPS_OAUTH2_SERVER_URL:" value
      config::set SERVICE_NPS_OAUTH2_SERVER_URL $value $SERVICE_CONFIG
    fi

    if [ -z "$SERVICE_NPS_OAUTH2_CLIENT_ID" ]; then
      inquirer::text "请输入 SERVICE_NPS_OAUTH2_CLIENT_ID:" value
      config::set SERVICE_NPS_OAUTH2_CLIENT_ID $value $SERVICE_CONFIG
    fi

    if [ -z "$SERVICE_NPS_OAUTH2_CLIENT_SECRET" ]; then
      inquirer::text "请输入 SERVICE_NPS_OAUTH2_CLIENT_SECRET:" value
      config::set SERVICE_NPS_OAUTH2_CLIENT_SECRET $value $SERVICE_CONFIG
    fi
  else
    if [ -z "$SERVICE_NPS_USERNAME" ]; then
      inquirer::text "请输入 SERVICE_NPS_USERNAME:" value "$(os::uuid)"
      config::set SERVICE_NPS_USERNAME $value $SERVICE_CONFIG
    fi

    if [ -z "$SERVICE_NPS_PASSWORD" ]; then
      inquirer::text "请输入 SERVICE_NPS_PASSWORD:" value "$(os::uuid)"
      config::set SERVICE_NPS_PASSWORD $value $SERVICE_CONFIG
    fi
  fi

  # load again
  config::load_file $SERVICE_CONFIG

  # @TODO
  export SERVICE_NPS_TUNNEL_PORT=$SERVICE_NPS_TUNNEL_PORT
  export SERVICE_NPS_OUT_PORTS=$SERVICE_NPS_OUT_PORTS
  #
  export SERVICE_NPS_DOMAIN=$SERVICE_NPS_DOMAIN
  export SERVICE_NPS_SECRET=$SERVICE_NPS_SECRET
  export SERVICE_NPS_USERNAME=$SERVICE_NPS_USERNAME
  export SERVICE_NPS_PASSWORD=$SERVICE_NPS_PASSWORD
  export SERVICE_NPS_OAUTH2_ENABLE=$SERVICE_NPS_OAUTH2_ENABLE
  export SERVICE_NPS_OAUTH2_SERVER_URL=$SERVICE_NPS_OAUTH2_SERVER_URL
  export SERVICE_NPS_OAUTH2_CLIENT_ID=$SERVICE_NPS_OAUTH2_CLIENT_ID
  export SERVICE_NPS_OAUTH2_CLIENT_SECRET=$SERVICE_NPS_OAUTH2_CLIENT_SECRET
}

check $@
